version: '3.7'

services:
   db:
     image: mariadb:10.3
     volumes:
       - ./sql/nhanes:/docker-entrypoint-initdb.d/
       - db_data:/var/lib/mysql
     restart: always
     env_file: ./docker/.env.mysql

   lh-ehr:
     # image: librehealth_ehr:${PHP_DOCKER_VERSION-php7.1}-apache
     build:
        context: .
        args:
          - PHP_DOCKER_TAG=7.1-apache
     volumes:
       - sites:/var/www/html/sites
       - ./docker/default_site/:/var/www/html/sites/default/
       - .:/var/www/html
     ports:
       - "8000:80"
     restart: always
     env_file: ./docker/.env.ehr
     depends_on:
       - db
volumes:
    db_data:
    sites:
